#pragma once
namespace TVP
{
    static inline constexpr auto  VK_FALG_MOUSE =    1;
    static inline constexpr auto  VK_FLAG_SHIFT =    2;
    static inline constexpr auto  VK_LBUTTON    = 0x01;
    static inline constexpr auto  VK_RBUTTON    = 0x02;
    static inline constexpr auto  VK_CANCEL     = 0x03;
    static inline constexpr auto  VK_MBUTTON    = 0x04;
    static inline constexpr auto  VK_BACK       = 0x08;
    static inline constexpr auto  VK_TAB        = 0x09;
    static inline constexpr auto  VK_CLEAR      = 0x0C;
    static inline constexpr auto  VK_RETURN     = 0x0D;
    static inline constexpr auto  VK_SHIFT      = 0x10;
    static inline constexpr auto  VK_CONTROL    = 0x11;
    static inline constexpr auto  VK_MENU       = 0x12;
    static inline constexpr auto  VK_PAUSE      = 0x13;
    static inline constexpr auto  VK_CAPITAL    = 0x14;
    static inline constexpr auto  VK_KANA       = 0x15;
    static inline constexpr auto  VK_HANGEUL    = 0x15;
    static inline constexpr auto  VK_HANGUL     = 0x15;
    static inline constexpr auto  VK_JUNJA      = 0x17;
    static inline constexpr auto  VK_FINAL      = 0x18;
    static inline constexpr auto  VK_HANJA      = 0x19;
    static inline constexpr auto  VK_KANJI      = 0x19;
    static inline constexpr auto  VK_ESCAPE     = 0x1B;
    static inline constexpr auto  VK_CONVERT    = 0x1C;
    static inline constexpr auto  VK_NONCONVERT = 0x1D;
    static inline constexpr auto  VK_ACCEPT     = 0x1E;
    static inline constexpr auto  VK_MODECHANGE = 0x1F;
    static inline constexpr auto  VK_SPACE      = 0x20;
    static inline constexpr auto  VK_PRIOR      = 0x21;
    static inline constexpr auto  VK_NEXT       = 0x22;
    static inline constexpr auto  VK_END        = 0x23;
    static inline constexpr auto  VK_HOME       = 0x24;
    static inline constexpr auto  VK_LEFT       = 0x25;
    static inline constexpr auto  VK_UP         = 0x26;
    static inline constexpr auto  VK_RIGHT      = 0x27;
    static inline constexpr auto  VK_DOWN       = 0x28;
    static inline constexpr auto  VK_SELECT     = 0x29;
    static inline constexpr auto  VK_PRINT      = 0x2A;
    static inline constexpr auto  VK_EXECUTE    = 0x2B;
    static inline constexpr auto  VK_SNAPSHOT   = 0x2C;
    static inline constexpr auto  VK_INSERT     = 0x2D;
    static inline constexpr auto  VK_DELETE     = 0x2E;
    static inline constexpr auto  VK_HELP       = 0x2F;
    static inline constexpr auto  VK_0          = 0x30;
    static inline constexpr auto  VK_1          = 0x31;
    static inline constexpr auto  VK_2          = 0x32;
    static inline constexpr auto  VK_3          = 0x33;
    static inline constexpr auto  VK_4          = 0x34;
    static inline constexpr auto  VK_5          = 0x35;
    static inline constexpr auto  VK_6          = 0x36;
    static inline constexpr auto  VK_7          = 0x37;
    static inline constexpr auto  VK_8          = 0x38;
    static inline constexpr auto  VK_9          = 0x39;
    static inline constexpr auto  VK_A          = 0x41;
    static inline constexpr auto  VK_B          = 0x42;
    static inline constexpr auto  VK_C          = 0x43;
    static inline constexpr auto  VK_D          = 0x44;
    static inline constexpr auto  VK_E          = 0x45;
    static inline constexpr auto  VK_F          = 0x46;
    static inline constexpr auto  VK_G          = 0x47;
    static inline constexpr auto  VK_H          = 0x48;
    static inline constexpr auto  VK_I          = 0x49;
    static inline constexpr auto  VK_J          = 0x4A;
    static inline constexpr auto  VK_K          = 0x4B;
    static inline constexpr auto  VK_L          = 0x4C;
    static inline constexpr auto  VK_M          = 0x4D;
    static inline constexpr auto  VK_N          = 0x4E;
    static inline constexpr auto  VK_O          = 0x4F;
    static inline constexpr auto  VK_P          = 0x50;
    static inline constexpr auto  VK_Q          = 0x51;
    static inline constexpr auto  VK_R          = 0x52;
    static inline constexpr auto  VK_S          = 0x53;
    static inline constexpr auto  VK_T          = 0x54;
    static inline constexpr auto  VK_U          = 0x55;
    static inline constexpr auto  VK_V          = 0x56;
    static inline constexpr auto  VK_W          = 0x57;
    static inline constexpr auto  VK_X          = 0x58;
    static inline constexpr auto  VK_Y          = 0x59;
    static inline constexpr auto  VK_Z          = 0x5A;
    static inline constexpr auto  VK_LWIN       = 0x5B;
    static inline constexpr auto  VK_RWIN       = 0x5C;
    static inline constexpr auto  VK_APPS       = 0x5D;
    static inline constexpr auto  VK_NUMPAD0    = 0x60;
    static inline constexpr auto  VK_NUMPAD1    = 0x61;
    static inline constexpr auto  VK_NUMPAD2    = 0x62;
    static inline constexpr auto  VK_NUMPAD3    = 0x63;
    static inline constexpr auto  VK_NUMPAD4    = 0x64;
    static inline constexpr auto  VK_NUMPAD5    = 0x65;
    static inline constexpr auto  VK_NUMPAD6    = 0x66;
    static inline constexpr auto  VK_NUMPAD7    = 0x67;
    static inline constexpr auto  VK_NUMPAD8    = 0x68;
    static inline constexpr auto  VK_NUMPAD9    = 0x69;
    static inline constexpr auto  VK_MULTIPLY   = 0x6A;
    static inline constexpr auto  VK_ADD        = 0x6B;
    static inline constexpr auto  VK_SEPARATOR  = 0x6C;
    static inline constexpr auto  VK_SUBTRACT   = 0x6D;
    static inline constexpr auto  VK_DECIMAL    = 0x6E;
    static inline constexpr auto  VK_DIVIDE     = 0x6F;
    static inline constexpr auto  VK_F1         = 0x70;
    static inline constexpr auto  VK_F2         = 0x71;
    static inline constexpr auto  VK_F3         = 0x72;
    static inline constexpr auto  VK_F4         = 0x73;
    static inline constexpr auto  VK_F5         = 0x74;
    static inline constexpr auto  VK_F6         = 0x75;
    static inline constexpr auto  VK_F7         = 0x76;
    static inline constexpr auto  VK_F8         = 0x77;
    static inline constexpr auto  VK_F9         = 0x78;
    static inline constexpr auto  VK_F10        = 0x79;
    static inline constexpr auto  VK_F11        = 0x7A;
    static inline constexpr auto  VK_F12        = 0x7B;
    static inline constexpr auto  VK_F13        = 0x7C;
    static inline constexpr auto  VK_F14        = 0x7D;
    static inline constexpr auto  VK_F15        = 0x7E;
    static inline constexpr auto  VK_F16        = 0x7F;
    static inline constexpr auto  VK_F17        = 0x80;
    static inline constexpr auto  VK_F18        = 0x81;
    static inline constexpr auto  VK_F19        = 0x82;
    static inline constexpr auto  VK_F20        = 0x83;
    static inline constexpr auto  VK_F21        = 0x84;
    static inline constexpr auto  VK_F22        = 0x85;
    static inline constexpr auto  VK_F23        = 0x86;
    static inline constexpr auto  VK_F24        = 0x87;
    static inline constexpr auto  VK_NUMLOCK    = 0x90;
    static inline constexpr auto  VK_SCROLL     = 0x91;
    static inline constexpr auto  VK_LSHIFT     = 0xA0;
    static inline constexpr auto  VK_RSHIFT     = 0xA1;
    static inline constexpr auto  VK_LCONTROL   = 0xA2;
    static inline constexpr auto  VK_RCONTROL   = 0xA3;
    static inline constexpr auto  VK_LMENU      = 0xA4;
    static inline constexpr auto  VK_RMENU      = 0xA5;

    static inline constexpr auto  VK_PROCESSKEY = 0xE5;
    static inline constexpr auto  VK_ATTN       = 0xF6;
    static inline constexpr auto  VK_CRSEL      = 0xF7;
    static inline constexpr auto  VK_EXSEL      = 0xF8;
    static inline constexpr auto  VK_EREOF      = 0xF9;
    static inline constexpr auto  VK_PLAY       = 0xFA;
    static inline constexpr auto  VK_ZOOM       = 0xFB;
    static inline constexpr auto  VK_NONAME     = 0xFC;
    static inline constexpr auto  VK_PA1        = 0xFD;
    static inline constexpr auto  VK_OEM_CLEAR  = 0xFE;

    static inline constexpr auto  VK_OEM_1      = 0xBA;   // ';:' for US
    static inline constexpr auto  VK_OEM_PLUS   = 0xBB;   // '+' any country
    static inline constexpr auto  VK_OEM_COMMA  = 0xBC;   // ',' any country
    static inline constexpr auto  VK_OEM_MINUS  = 0xBD;   // '-' any country
    static inline constexpr auto  VK_OEM_PERIOD = 0xBE;   // '.' any country
    static inline constexpr auto  VK_OEM_2      = 0xBF;   // '/?' for US
    static inline constexpr auto  VK_OEM_3      = 0xC0;   // '`~' for US
    static inline constexpr auto  VK_OEM_4      = 0xDB;  //  '[{' for US
    static inline constexpr auto  VK_OEM_5      = 0xDC;  //  '\|' for US
    static inline constexpr auto  VK_OEM_6      = 0xDD;  //  ']}' for US
    static inline constexpr auto  VK_OEM_7      = 0xDE;  //  ''"' for US
    static inline constexpr auto  VK_OEM_8      = 0xDF;

    static inline constexpr auto  TVP_SS_SHIFT  =  0x01;
    static inline constexpr auto  TVP_SS_ALT    =  0x02;
    static inline constexpr auto  TVP_SS_CTRL   =  0x04;
    static inline constexpr auto  TVP_SS_LEFT   =  0x08;
    static inline constexpr auto  TVP_SS_RIGHT  =  0x10;
    static inline constexpr auto  TVP_SS_MIDDLE =  0x20;
    static inline constexpr auto  TVP_SS_DOUBLE =  0x40;
    static inline constexpr auto  TVP_SS_REPEAT =  0x80;

    static inline constexpr auto  VK_PAD_FIRST	= 0x1B0; // first PAD related key code
    static inline constexpr auto  VK_PADLEFT	= 0x1B5;
    static inline constexpr auto  VK_PADUP		= 0x1B6;
    static inline constexpr auto  VK_PADRIGHT	= 0x1B7;
    static inline constexpr auto  VK_PADDOWN	= 0x1B8;
    static inline constexpr auto  VK_PAD1		= 0x1C0;
    static inline constexpr auto  VK_PAD2		= 0x1C1;
    static inline constexpr auto  VK_PAD3		= 0x1C2;
    static inline constexpr auto  VK_PAD4		= 0x1C3;
    static inline constexpr auto  VK_PAD5		= 0x1C4;
    static inline constexpr auto  VK_PAD6		= 0x1C5;
    static inline constexpr auto  VK_PAD7		= 0x1C6;
    static inline constexpr auto  VK_PAD8		= 0x1C7;
    static inline constexpr auto  VK_PAD9		= 0x1C8;
    static inline constexpr auto  VK_PAD10		= 0x1C9;
    static inline constexpr auto  VK_PADANY		= 0x1DF; // returns whether any one of pad buttons are pressed,
                                                         // in System.getKeyState
    static inline constexpr auto  VK_PAD_LAST   = 0x1DF; // last PAD related key code

    enum
    {
        ssShift  = TVP_SS_SHIFT,
        ssAlt    = TVP_SS_ALT,
        ssCtrl   = TVP_SS_CTRL,
        ssLeft   = TVP_SS_LEFT,
        ssRight  = TVP_SS_RIGHT,
        ssMiddle = TVP_SS_MIDDLE,
        ssDouble = TVP_SS_DOUBLE,
        ssRepeat = TVP_SS_REPEAT,
    };
}